const {
  PORT,
  PAGE_NUMBER,
  PAGE_SIZE,

  JWT_SECRET_KEY,
  ACCESS_TOKEN_EXPIRES_IN,

  MONGO_URI,

  NOTIFICATION_MAIL_FROM,
  NOTIFICATION_MAIL_USERNAME,
  NOTIFICATION_MAIL_PASSWORD,

  BOT_TELEGRAM_ACCESS_TOKEN,
} = process.env;

module.exports = {
  PORT: PORT || 80,
  PAGE_NUMBER_DEFAULT: parseInt(PAGE_NUMBER || '1', 10),
  PAGE_SIZE_DEFAULT: parseInt(PAGE_SIZE || '10', 10),

  JWT_SECRET_KEY,
  ACCESS_TOKEN_EXPIRES_IN: parseInt(ACCESS_TOKEN_EXPIRES_IN || '86400', 10),

  MONGO_URI,

  NOTIFICATION_MAIL_FROM: NOTIFICATION_MAIL_FROM || 'atrati',
  NOTIFICATION_MAIL_USERNAME,
  NOTIFICATION_MAIL_PASSWORD,

  BOT_TELEGRAM_ACCESS_TOKEN,
};
